[fa] fix out of context bot translations
Laravel-Lang/actions pull request #496
Opened 2024-03-13 11:34 UTC by mokhosh

This fixes AI generated translations which are honestly terrible.

Question with a little context: In English the infinitive form and the imperative form are the same in many situations. Like in the case of "add", and sometimes they're different, like you have "impersonate" and "impersonation" in these files.
In Farsi, they are almost always different. Which one do you think should we default to, the infinitive form, or the imperative?

This can be merged regardless of the question above, since I've tried to stick to Farsi applications terminology.

2024-03-13 11:41 UTC, andrey-helldar commented
When translating into other languages, the same problem occurs. I think you should use the infinitive form of the verb, as it is most often appropriate in the context. But I could be wrong.

@Laravel-Lang/laravel-lang, what do you think about using the verb form?

2024-03-13 11:58 UTC, ariaieboy requested changes
لطفا موارد ذکر شده را بررسی کنید

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/json.json
> +    "Assign": "واگذاری",
فکر نمیکنم assign کردن خیلی مرتبط باشه با واگذاری میشه برای این مورد ترجمه بهتری در نظر گرفت

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/json.json
> +    "Create": "كردن",
اینجا هم فکر میکنم اشتباه ترجمه شده و ترجمه درستی نیست

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/json.json
> +    "Export": "صدور",
این مورد هم فکر میکنم ترجمه بهتری میتونیم انتخاب کنیم خیلی صدور ربطی به export نداره

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/json.json
> +    "Switch": "تغییر",
این مورد فکر میکنم میتونه بهتر ترجمه بشه

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/php.json
> +    "assign": "واگذاری",
این مورد مثل بالا میتونه بهتر ترجمه بشه

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/json.json
> +    "Expand": "باز کردن",
فاصله بین کلمه باز و کردن باید حذف بشه

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/json.json
> +    "Expand All": "باز کردن همه",
همچنین اینجا فاصله بین باز و کردن باید حذف بشه

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/php.json
> +    "expand": "باز کردن",
مثل بالا فاصله بین کلمات حذف بشه

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/php.json
> +    "export": "صدور",
همانند بالا باید ترجمه بهتری انتخاب شود

2024-03-13 11:58 UTC, ariaieboy commented on locales/fa/php.json
> +    "switch": "تغییر",
این مورد هم مثل بالا بهتر ترجمه دیگه ای انتخاب بشه

2024-03-13 12:01 UTC, mokhosh commented on locales/fa/json.json
> +    "Assign": "واگذاری",
منظورش assign کردن یه ماموریت نیست؟ که میگیم واگذاری ماموریت یا وظیفه؟

2024-03-13 12:03 UTC, mokhosh commented on locales/fa/json.json
> +    "Create": "كردن",
اصلاح شد

2024-03-13 12:04 UTC, mokhosh commented on locales/fa/json.json
> +    "Switch": "تغییر",
اینو فقط برای consistency با پایینیش یکی کردم. پیشنهادی دارید؟

2024-03-13 12:07 UTC, ariaieboy commented on locales/fa/json.json
> +    "Assign": "واگذاری",
دقیق نمیدونم این Assign کجا به کار رفته ولی معمولا وقتی دوتا چیز میخوان به هم ربط بدن از assign کردن استفاده میکنند مثل اینکه یکسری middleware را assign می کنند به یکسری route و... 

فکر میکنم تخصیص میتونه بیشتر معنی را برسونه ولی بازم باید توی ui ببینیم کجا هست و کدوم کلمه معنای بهتری میده

2024-03-13 12:08 UTC, mokhosh commented on locales/fa/json.json
> +    "Expand": "باز کردن",
فکر میکنم از نظر نگارشی اینجا فاصله درسته.
ولی کلا ترجمه‌ها یکدست نیست. خوبه یه رفرنس به عنوان شیوه‌نامه انتخاب کنیم و همه طبق همون باشه.

2024-03-13 12:09 UTC, ariaieboy commented on locales/fa/json.json
> +    "Export": "صدور",
معنی export توی اینجا میشه خروجی گرفتن و با اون معنای صادرات فرق میکنه باید کلمه ای باشه که مرتبط باشه با خروجی گرفتن.

2024-03-13 12:15 UTC, ariaieboy commented on locales/fa/json.json
> +    "Expand": "باز کردن",
من چند وقت پیش تمام ترجمه ها را بررسی کردم و سعی کردم همه ترجمه ها یکدست بشه منتهای مراتب از اونجایی که هر چند وقت یکبار تغییرات جدید میاد و بعضی هاش بات ترجمه میکنه باز بهم میریزه نیاز هست که همواره چک بشه.
از لحاظ نگارشی درسته باید فاصله باشه ولی چون این ترجمه های معمولا توی دکمه استفاده میشه فاصله بین کلمات زیاد جالب نمیشه. 
ولی خوب اصولیش این هست مطابق نگارش زبان بریم جلو

2024-03-13 12:20 UTC, mokhosh commented on locales/fa/json.json
> +    "Export": "صدور",
بله صادرات که ترجمه ربات بوده.
اما صدور رو من توی خیلی از برنامه های فارسی دیدم. مثلا برنامه هلو رو ببینید زده «صدور سند». یا مثلا چلیپا و خیلی برنامه های دیگه.
این لینکها هم رفرنس رسمی نیستن اما نشون میده این کلمه معموله توی فضای تک فارسی:

https://www.ir-translate.com/PU/Dictionary/WordPage.aspx?eid=131854

https://techbord.ir/terms/export-%D8%B5%D8%AF%D9%88%D8%B1-%D9%81%D8%A7%DB%8C%D9%84

2024-03-13 12:21 UTC, mokhosh commented on locales/fa/json.json
> +    "Switch": "تغییر",
موافقم. پس پایینی رو هم میکنم تعویض نقش که مثل هم باشن.

2024-03-13 12:24 UTC, mokhosh commented on locales/fa/json.json
> +    "Expand": "باز کردن",
آره برای همین میگم یه رفرنس داشته باشیم که اگر عزیز دیگه ای هم PR زد بهش بدیم طبق همون منظم کنه بعد مرج بشه.
پس موافقید فاصله‌ها طبق اصول نگارشی یکدست باشه؟

2024-03-13 13:04 UTC, ariaieboy commented on locales/fa/json.json
> +    "Export": "صدور",
فعلا من چیز بهتری به نظرم نمیاد با همین صدور میریم جلو تا باز مورد بهتری پیدا بشه

2024-03-13 13:05 UTC, ariaieboy commented on locales/fa/json.json
> +    "Expand": "باز کردن",
رفرنس خاصی اگر مد نظرتون هست توی یک دیسکاشن بذارید بررسی میکنیم اگر اوکی بود همان به عنوان معیار معرفی میکنیم و هر PR مربوط به زبان فارسی بود لینک میدیم به اونجا که همه طبق یک معیاری برن جلو

2024-03-13 13:17 UTC, mokhosh commented on locales/fa/json.json
> +    "Expand": "باز کردن",
انگار این رپو بخش دیسکاشن نداره. به نظرم دستور خط فارسی فرهنگستان شیوه نامه خوب و مفصلیه.

این آخرین نسخه ست:

https://apll.ir/wp-content/uploads/2023/07/Dastour-e-Khat-17.04.1402.pdf

کجا بذاریم که افراد اطلاع داشته باشن؟ کامنت کنیم؟

2024-03-13 13:19 UTC, mokhosh commented on locales/fa/json.json
> +    "Expand": "باز کردن",
اینم شاید مفید باشه برای یه رفرنس فوری برای کسایی که حوصله ندارن:

https://fa.wikipedia.org/wiki/%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7:%D8%B4%DB%8C%D9%88%D9%87_%D8%AE%D8%B7_%D9%81%D8%A7%D8%B1%D8%B3%DB%8C

2024-03-14 19:25 UTC, mokhosh commented on locales/fa/json.json
> +    "Assign": "واگذاری",
بررسی کردید این مورد رو؟

2024-03-14 19:26 UTC, mokhosh commented on locales/fa/json.json
> +    "Expand": "باز کردن",
اینارم اگر بگید کجا بذاریم فکر کنم دیگه resolve شده همه موارد

2024-03-23 11:20 UTC, andrey-helldar commented on locales/fa/json.json
> +    "Expand": "باز کردن",
test

2024-03-23 11:22 UTC, ariaieboy commented on locales/fa/json.json
> +    "Assign": "واگذاری",
```suggestion
    "Assign": "انتصاب",
```

2024-03-23 11:22 UTC, ariaieboy commented on locales/fa/php.json
> +    "assign": "واگذاری",
```suggestion
    "assign": "انتصاب",
```

2024-03-23 11:24 UTC, andrey-helldar commented
ممنون

2024-03-23 11:24 UTC, merged